---
- name: Install Go version using GVM
  shell: |
    export GVM_ROOT="{{ ansible_env.HOME }}/.gvm"
    source $GVM_ROOT/scripts/gvm
    gvm install go{{ go_version }} -B
  environment:
    GVM_ROOT: "{{ ansible_env.HOME }}/.gvm"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.gvm/gos/go{{ go_version }}"

- name: Set default Go version using GVM
  shell: |
    export GVM_ROOT="{{ ansible_env.HOME }}/.gvm"
    source $GVM_ROOT/scripts/gvm
    gvm use go{{ go_version }} --default
  environment:
    GVM_ROOT: "{{ ansible_env.HOME }}/.gvm"
  args:
    executable: /bin/bash