# tasks/install_nvm.yml
- name: Create NVM directory
  ansible.builtin.file:
    path: "{{ nvm_directory }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download NVM installation script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    dest: "/tmp/install_nvm.sh"
    mode: '0755'

- name: Run NVM installation script
  ansible.builtin.shell: bash /tmp/install_nvm.sh
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ nvm_directory }}"

- name: Set NVM environment variables system-wide
  ansible.builtin.copy:
    content: |
      export NVM_DIR="{{ nvm_directory }}"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    dest: /etc/profile.d/nvm.sh
    mode: '0755'

- name: Reload shell profile
  ansible.builtin.shell: source /etc/profile.d/nvm.sh
  args:
    executable: /bin/bash