# tasks/install_node.yml
- name: Load NVM and install Node.js
  ansible.builtin.shell: |
    export NVM_DIR="{{ nvm_directory }}"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install {{ node_version }}
    nvm alias default {{ node_version }}
  args:
    executable: /bin/bash