# meta/main.yml
---
galaxy_info:
  author: Todd Zmijewski
  description: Install NVM and set up Node.js system-wide on Debian/Ubuntu-based systems.
  role_name: nvm
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  min_ansible_version: 2.9
dependencies: []