---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - gnupg
      - curl
    state: present
    update_cache: yes

- name: Download and install Bazel GPG key
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present

- name: Add Bazel APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8"
    state: present

- name: Install Bazel
  apt:
    name: bazel
    state: present