---
- name: Install VS Code extensions
  become: no
  shell: code --install-extension {{ item }}
  loop:
    - bazelbuild.vscode-bazel
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{ item }}"