---
# Task to configure Cassandra

- name: Configure Cassandra
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/cassandra.yaml
    owner: cassandra
    group: cassandra
    mode: '0644'

- name: Create a global environment file for Cassandra
  copy:
    content: |
      export CASSANDRA_HOME=/usr/share/cassandra
      export PATH=$PATH:$CASSANDRA_HOME/bin
    dest: /etc/profile.d/cassandra.sh
    owner: root
    group: root
    mode: '0644'

- name: Ensure Cassandra environment is loaded for all users
  shell: source /etc/profile.d/cassandra.sh
  args:
    executable: /bin/bash

- name: Enable Cassandra service to start on boot
  systemd:
    name: cassandra
    enabled: true
    state: started
