---
- name: Create systemd service file for Cassandra
  template:
    src: cassandra.service.j2
    dest: /etc/systemd/system/cassandra.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes