---
# Task to configure K3s access for multiple users

- name: Create .kube directory for each user
  file:
    path: /home/{{ item }}/.kube
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  with_items: "{{ k3s_users }}"

- name: Copy K3s kubeconfig to each user's home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ item }}/.kube/config
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  with_items: "{{ k3s_users }}"

- name: Ensure /usr/local/bin is added to system-wide PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/bin'
    state: present