---
- name: Install VS Code extensions
  become: no
  shell: code --install-extension {{ item }}
  loop: "{{ vs_code_extensions }}"
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{ item }}"