---
# Install Python Version and Configure Defaults

# Install Python version using pyenv
- name: Install Python version using pyenv
  shell: |
    export PYENV_ROOT="/opt/pyenv"
    export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
    pyenv install -s {{ python_version }}
  args:
    executable: /bin/bash
  register: python_install_result
  failed_when: "'already exists' not in python_install_result.stderr and python_install_result.rc != 0"
  changed_when: "'already exists' not in python_install_result.stderr"

# Set default Python version globally
- name: Set default Python version globally
  shell: |
    export PYENV_ROOT="/opt/pyenv"
    export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    pyenv global {{ python_version }}
  args:
    executable: /bin/bash
  register: python_global_result
  failed_when: python_global_result.rc != 0
  changed_when: python_global_result.rc == 0

# Create a python alias if missing
- name: Ensure python points to python3
  file:
    src: "/opt/pyenv/shims/python3"
    dest: "/opt/pyenv/shims/python"
    state: link
    force: yes

# Verify Python and pip installation
- name: Verify Python and pip installation
  shell: |
    export PYENV_ROOT="/opt/pyenv"
    export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
    python --version && pip3 --version
  args:
    executable: /bin/bash
  register: python_pip_check
  failed_when: python_pip_check.rc != 0
  changed_when: false

# Debug Python and pip version output
- name: Debug Python and pip version output
  debug:
    msg:
      - "Python Version: {{ python_pip_check.stdout_lines[0] }}"
      - "Pip Version: {{ python_pip_check.stdout_lines[1] }}"

# Verify pyenv command accessibility
- name: Verify pyenv command accessibility
  shell: |
    export PYENV_ROOT="/opt/pyenv"
    export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
    pyenv --version
  args:
    executable: /bin/bash
  register: pyenv_check
  failed_when: pyenv_check.rc != 0
  changed_when: false

# Debug pyenv version output
- name: Debug pyenv version output
  debug:
    var: pyenv_check.stdout

# Ensure Python and pip are accessible by external programs
- name: Test Python and pip accessibility by external programs
  shell: |
    export PYENV_ROOT="/opt/pyenv"
    export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
    python -c "import sys; print('Python is accessible')" && pip3 list
  args:
    executable: /bin/bash
  register: external_program_check
  failed_when: external_program_check.rc != 0
  changed_when: false

# Debug external program accessibility test result
- name: Debug external program accessibility test result
  debug:
    var: external_program_check.stdout
