---
- name: Ensure dependencies are installed
  apt:
    name:
      - unzip
      - wget
    state: present
    update_cache: yes

- name: Download Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform.zip"

- name: Unzip Terraform
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
    mode: '0755'

- name: Verify Terraform installation
  command: terraform --version
  register: terraform_version_output
  changed_when: false

- name: Display Terraform version
  debug:
    msg: "{{ terraform_version_output.stdout }}"