---
- name: Install VS Code extensions
  become: no
  shell: code --install-extension {{ item }}
  loop:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{ item }}"
