- name: Install VS Code extensions
  become: no
  shell: |
    if ! code --list-extensions | grep -q {{ item }}; then
      code --install-extension {{ item }}
    fi
  loop:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
  args:
    executable: /bin/bash
  retries: 3
  delay: 5
  register: vscode_install_result
  until: vscode_install_result.rc == 0