---
- name: Install Java version using SDKMAN
  shell: |
    export SDKMAN_DIR="{{ ansible_env.HOME }}/.sdkman"
    source $SDKMAN_DIR/bin/sdkman-init.sh
    sdk install java {{ java_version }}
  environment:
    SDKMAN_DIR: "{{ ansible_env.HOME }}/.sdkman"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.sdkman/candidates/java/{{ java_version }}"

- name: Set default Java version using SDKMAN
  shell: |
    export SDKMAN_DIR="{{ ansible_env.HOME }}/.sdkman"
    source $SDKMAN_DIR/bin/sdkman-init.sh
    sdk default java {{ java_version }}
  environment:
    SDKMAN_DIR: "{{ ansible_env.HOME }}/.sdkman"
  args:
    executable: /bin/bash
