---
# Install Java version using SDKMAN
- name: Install Java version using SDKMAN
  shell: |
    export SDKMAN_DIR="/opt/sdkman"
    source $SDKMAN_DIR/bin/sdkman-init.sh
    sdk install java {{ java_version }}
  args:
    executable: /bin/bash
  register: java_install_result
  failed_when: "'Stop! java' in java_install_result.stdout"
  changed_when: "'Done installing!' in java_install_result.stdout"

- name: Debug Java installation output
  debug:
    var: java_install_result.stdout

# Verify SDKMAN Java directory exists
- name: Verify SDKMAN Java directory exists
  stat:
    path: "/opt/sdkman/candidates/java/{{ java_version }}"
  register: java_sdkman_directory

# Create or update the 'current' symlink for SDKMAN Java
- name: Ensure 'current' symlink for SDKMAN Java points to installed version
  file:
    src: "/opt/sdkman/candidates/java/{{ java_version }}"
    dest: "/opt/sdkman/candidates/java/current"
    state: link
  when: java_sdkman_directory.stat.exists

# Add JAVA_HOME to global profile
- name: Add JAVA_HOME to global profile
  copy:
    dest: /etc/profile.d/sdkman.sh
    content: |
      export SDKMAN_DIR="/opt/sdkman"
      [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
      export JAVA_HOME="$SDKMAN_DIR/candidates/java/current"
      export PATH="$JAVA_HOME/bin:$PATH"
    owner: root
    group: root
    mode: '0755'

# Reload global profile for current session
- name: Reload global profile for current session
  shell: source /etc/profile.d/sdkman.sh
  args:
    executable: /bin/bash

# Verify JAVA_HOME is set
- name: Verify JAVA_HOME is set
  shell: echo $JAVA_HOME
  register: java_home_output
  args:
    executable: /bin/bash

- name: Debug JAVA_HOME
  debug:
    var: java_home_output.stdout

# Verify Java installation
- name: Verify Java installation
  shell: |
    export SDKMAN_DIR="/opt/sdkman"
    source $SDKMAN_DIR/bin/sdkman-init.sh
    java -version
  register: java_version_output
  args:
    executable: /bin/bash

- name: Debug Java version output
  debug:
    var: java_version_output.stdout