---
# Ensure required dependencies are installed
- name: Ensure dependencies are installed
  apt:
    name:
      - zip
      - unzip
      - curl
      - wget
    state: present
    update_cache: yes

# Create a global SDKMAN directory
- name: Create a global SDKMAN directory
  file:
    path: /opt/sdkman
    state: directory
    owner: root
    group: root
    mode: '0755'

# Check if SDKMAN is already installed
- name: Check if SDKMAN is already installed
  stat:
    path: /opt/sdkman/bin/sdkman-init.sh
  register: sdkman_exists

# Download and install SDKMAN into /opt/sdkman
- name: Download and install SDKMAN into /opt/sdkman
  shell: |
    curl -s "https://get.sdkman.io" | bash
    [ -d /root/.sdkman ] && mv /root/.sdkman/* /opt/sdkman/ || true
    rmdir /root/.sdkman || true
  args:
    executable: /bin/bash
  when: not sdkman_exists.stat.exists

# Set up SDKMAN environment variables globally
- name: Set up SDKMAN environment variables globally
  copy:
    dest: /etc/profile.d/sdkman.sh
    content: |
      export SDKMAN_DIR="/opt/sdkman"
      [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
    owner: root
    group: root
    mode: '0755'

- name: Reload global environment variables for current session
  shell: . /etc/profile.d/sdkman.sh  # Use dot command for compatibility
  args:
    executable: /bin/bash