---
- name: Ensure dependencies are installed
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Download AWS CLI
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"

- name: Unzip AWS CLI
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Install AWS CLI
  shell: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws