---
- name: Install VS Code extensions
  become: false
  shell: code --install-extension {{ item }}
  loop:
    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
    - twxs.cmake
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{ item }}"