---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Inkscape PPA repository
  apt_repository:
    repo: "ppa:inkscape.dev/stable"
    state: present
    update_cache: yes

- name: Install Inkscape
  apt:
    name: inkscape
    state: present