---
- name: Install Google Chrome
  hosts: all
  become: yes

  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Download Google Chrome GPG key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
        update_cache: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present