---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: yes

- name: Install GIMP
  apt:
    name: gimp
    state: present